# Generated by Django 4.2.11 on 2024-05-04 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('aceptaResponsabilidad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Desperfecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('legajo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('fechaIngreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('entreCalleA', models.CharField(max_length=100)),
                ('entreCalleB', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('aCargoDe', models.CharField(max_length=100)),
                ('apertura', models.DateField()),
                ('cierre', models.DateField(blank=True, null=True)),
                ('comentarios', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='vecino',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gmuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'vecino'), (2, 'inspector')], default=1),
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('idReclamoUnificado', models.IntegerField()),
                ('desperfecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.desperfecto')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.personal')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sitio')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vecino')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('horarios', models.CharField(max_length=30)),
                ('medioDeContacto', models.CharField(max_length=100)),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vecino')),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MovimientoReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.reclamo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.personal')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=150)),
                ('causa', models.CharField(max_length=4000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.denuncia')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='reclamos/')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.reclamo')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='promociones/')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.promocion')),
            ],
        ),
        migrations.AddField(
            model_name='desperfecto',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rubro'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sitio'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='vecino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vecino'),
        ),
    ]
