# Generated by Django 4.2.11 on 2024-05-05 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_denuncia_desperfecto_personal_rubro_sitio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncia',
            old_name='vecino',
            new_name='denunciado',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='denunciante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocion',
            name='validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Abierta'), (2, 'Cerrada')], default=1),
        ),
        migrations.AlterField(
            model_name='gmuser',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'En revision'), (2, 'Abierto'), (3, 'Cerrado')], default=1),
        ),
    ]
