# Generated by Django 4.2.11 on 2024-06-29 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_userregistercode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='denunciado',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='vecino',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='denunciante',
            field=models.ForeignKey(db_column='documento', on_delete=django.db.models.deletion.CASCADE, to='main_app.vecino'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='personal',
            field=models.ForeignKey(db_column='legajo', on_delete=django.db.models.deletion.CASCADE, to='main_app.personal'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='vecino',
            field=models.ForeignKey(db_column='documento', on_delete=django.db.models.deletion.CASCADE, to='main_app.vecino'),
        ),
        migrations.AlterField(
            model_name='vecino',
            name='barrio',
            field=models.ForeignKey(db_column='codigo_barrio', on_delete=django.db.models.deletion.CASCADE, to='main_app.barrio'),
        ),
        migrations.CreateModel(
            name='UserVecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vecino')),
            ],
        ),
        migrations.CreateModel(
            name='UserPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.personal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DenunciaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='denuncias/')),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.denuncia')),
            ],
        ),
        migrations.CreateModel(
            name='DenunciadoReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.denuncia')),
                ('denunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vecino')),
            ],
        ),
    ]
