# Generated by Django 4.2.11 on 2024-06-09 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_userregistercode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='password',
        ),
        migrations.AlterField(
            model_name='vecino',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
