# Generated by Django 4.2.11 on 2024-06-09 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_personal_password_alter_vecino_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenpromocion',
            options={'verbose_name_plural': 'Imagen promociones'},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name_plural': 'Personal'},
        ),
        migrations.AlterModelOptions(
            name='promocion',
            options={'verbose_name_plural': 'Promociones'},
        ),
        migrations.AlterField(
            model_name='personal',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
