# Generated by Django 4.2.11 on 2024-06-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_denuncia_denunciado_remove_personal_usuario_and_more'),
        ('main_app', '0006_alter_imagenpromocion_options_alter_personal_options_and_more'),
    ]

    operations = [
    ]
