# Generated by Django 4.2.11 on 2024-06-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_merge_20240629_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='fechaIngreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
