# Generated by Django 4.2.11 on 2024-06-29 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_personal_password_alter_personal_fechaingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='aceptaResponsabilidad',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='idReclamoUnificado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='personal',
            field=models.ForeignKey(blank=True, db_column='legajo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.personal'),
        ),
    ]
