# Generated by Django 4.2.11 on 2024-06-30 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_promocion_nombre_promocion_rubro_promocion_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='categoria',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='rubro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='PersonalRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.personal')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rubro')),
            ],
        ),
    ]
