# Generated by Django 4.2.11 on 2024-07-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_reclamo_vecino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='horarios',
            field=models.TextField(),
        ),
    ]
