# Generated by Django 4.2.11 on 2024-07-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_promocion_horarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='denunciaimagen',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='denuncias/'),
        ),
        migrations.AlterField(
            model_name='denunciaimagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='denuncias/'),
        ),
    ]
